---

- name: Add new FortiWeb HTTP Content Routing Policy Matchlist for {{ fwb_http_content_routing_policy.name + ' - ' + http_content_routing_matchlist.id }}
  ansible.builtin.uri:
    method: POST
    url: "{{ fwb_api_endpoint.http_content_routing_policy_matchlist | format(fwb_http_content_routing_policy.name, http_content_routing_matchlist.id) }}"
    body_format: "form-urlencoded"
    validate_certs: false
    return_content: true
    status_code: [200, 500]
    headers:
      "Authorization": "{{ fwb_api_token }}"
      "Content-Type": "application/x-www-form-urlencoded"
    body:
      "match-object={{ http_content_routing_matchlist.match_object }}&\
      match-condition={{ http_content_routing_matchlist.match_condition }}&\
      match-expression={{ http_content_routing_matchlist.match_expression }}&\
      concatenate={{ http_content_routing_matchlist.concatenate }}"
  register: fwb_http_content_routing_policy_matchlist_post_result
  # only add new match list if there's no match list yet
  when:
    - fwb_http_content_routing_policy_get_result.json.results['sz_content-routing-match-list'] == 0
  changed_when: fwb_http_content_routing_policy_matchlist_post_result.status == 200
  failed_when: fwb_http_content_routing_policy_matchlist_post_result.json.errcode is defined
  tags: [fwb_http_content_routing_policy_matchlist]

- name: Update FortiWeb HTTP Content Routing Policy Matchlist for {{ fwb_http_content_routing_policy.name + ' - ' + http_content_routing_matchlist.id }}
  ansible.builtin.uri:
    method: PUT
    url: "{{ fwb_api_endpoint.http_content_routing_policy_matchlist | format(fwb_http_content_routing_policy.name, http_content_routing_matchlist.id) }}"
    body_format: "form-urlencoded"
    validate_certs: "false"
    return_content: "true"
    status_code: [200]
    headers:
      "Authorization": "{{ fwb_api_token }}"
      "Content-Type": "application/x-www-form-urlencoded"
    body:
      "match-object={{ http_content_routing_matchlist.match_object }}&\
      match-condition={{ http_content_routing_matchlist.match_condition }}&\
      match-expression={{ http_content_routing_matchlist.match_expression }}&\
      concatenate={{ http_content_routing_matchlist.concatenate }}"
  register: fwb_http_content_routing_policy_matchlist_put_result
  when:
    - fwb_http_content_routing_policy_get_result.json.results['sz_content-routing-match-list'] != 0
  # changed_when: fwb_http_content_routing_policy_matchlist_put_result.status == 200
  failed_when: fwb_http_content_routing_policy_matchlist_put_result.json.errcode is defined
  tags: [fwb_http_content_routing_policy_matchlist]
